# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  buildConfiguration: 'Release'
  packageVersion: '1.0.$(Build.BuildId)'


stages:
  - stage: 'BuildandTest'
    jobs:
    - job: Build
      displayName: 'Build and package'
      pool:
        vmImage: 'windows-latest'
      steps:
      - task: UseDotNet@2
        displayName: 'Install DotNet'
        inputs:
          packageType: 'sdk'
          version: '6.0.x'

      - task: SonarCloudPrepare@3
        displayName: 'Prepare sonarQube'
        inputs:
          SonarQube: 'SonarQube cloud'
          organization: 'devopspractice-2025'
          scannerMode: 'dotnet'
          projectKey: '9060128d289ee88e4b1ca57aeff5236ec1acd1ab'
          projectName: 'pipelines-dotnet-core.git'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
          vstsFeed: 'bc03c712-44c4-4932-87ba-ac35eaa10b33/0d882750-e9f7-4349-9c31-ece9b225e1fc'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration  $(buildConfiguration)'

      - task: SonarCloudAnalyze@3
        displayName: 'Code analysis'
        inputs:
          jdkversion: 'JAVA_HOME_17_X64'
          
      - task: DotNetCoreCLI@2
        displayName: 'dotnet pack'
        inputs:
          command: 'pack'
          packagesToPack: '**/*.csproj'
          configuration: '$(buildConfiguration)'
          versioningScheme: 'byEnvVar'
          versionEnvVar: 'packageVersion'
    
      - task: DotNetCoreCLI@2
        displayName: 'dotnet push'
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: 'bc03c712-44c4-4932-87ba-ac35eaa10b33/0d882750-e9f7-4349-9c31-ece9b225e1fc'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
